-   id: record-precommit-ran
    name: Record Pre-commit Usage
    description: Records a user github username or email address to verify theyve run pre-commit at least once.
    entry: record-precommit-ran
    language: python
    stages: [pre-commit]
    minimum_pre_commit_version: 3.2.0
    always_run: true